tess_map={'afrikaans': {'tess': 'afr', 'google': 'af'}, 'amharic': {'tess': 'amh', 'google': 'am'}, 'arabic': {'tess': 'ara', 'google': 'ar'}, 'assamese': {'tess': 'asm', 'google': 'as'}, 'azerbaijani': {'tess': 'aze', 'google': 'az'}, 'belarusian': {'tess': 'bel', 'google': 'be'}, 'bengali': {'tess': 'ben', 'google': 'bn'}, 'bosnian': {'tess': 'bos', 'google': 'bs'}, 'bulgarian': {'tess': 'bul', 'google': 'bg'}, 'catalan': {'tess': 'cat', 'google': 'ca'}, 'cebuano': {'tess': 'ceb', 'google': 'ceb'}, 'czech': {'tess': 'ces', 'google': 'cs'}, 'chinese (simplified)': {'tess': 'chi_sim', 'google': 'zh-CN'}, 'chinese (traditional)': {'tess': 'chi_tra', 'google': 'zh-TW'}, 'corsican': {'tess': 'cos', 'google': 'co'}, 'welsh': {'tess': 'cym', 'google': 'cy'}, 'danish': {'tess': 'dan', 'google': 'da'}, 'german': {'tess': 'deu', 'google': 'de'}, 'greek': {'tess': 'ell', 'google': 'el'}, 'english': {'tess': 'eng', 'google': 'en'}, 'esperanto': {'tess': 'epo', 'google': 'eo'}, 'estonian': {'tess': 'est', 'google': 'et'}, 'basque': {'tess': 'eus', 'google': 'eu'}, 'persian': {'tess': 'fas', 'google': 'fa'}, 'finnish': {'tess': 'fin', 'google': 'fi'}, 'french': {'tess': 'fra', 'google': 'fr'}, 'irish': {'tess': 'gle', 'google': 'ga'}, 'galician': {'tess': 'glg', 'google': 'gl'}, 'gujarati': {'tess': 'guj', 'google': 'gu'}, 'hebrew': {'tess': 'heb', 'google': 'iw'}, 'hindi': {'tess': 'hin', 'google': 'hi'}, 'croatian': {'tess': 'hrv', 'google': 'hr'}, 'hungarian': {'tess': 'hun', 'google': 'hu'}, 'indonesian': {'tess': 'ind', 'google': 'id'}, 'icelandic': {'tess': 'isl', 'google': 'is'}, 'italian': {'tess': 'ita', 'google': 'it'}, 'javanese': {'tess': 'jav', 'google': 'jw'}, 'japanese': {'tess': 'jpn', 'google': 'ja'}, 'kannada': {'tess': 'kan', 'google': 'kn'}, 'georgian': {'tess': 'kat', 'google': 'ka'}, 'kazakh': {'tess': 'kaz', 'google': 'kk'}, 'khmer': {'tess': 'khm', 'google': 'km'}, 'kyrgyz': {'tess': 'kir', 'google': 'ky'}, 'korean': {'tess': 'kor', 'google': 'ko'}, 'lao': {'tess': 'lao', 'google': 'lo'}, 'latin': {'tess': 'lat', 'google': 'la'}, 'latvian': {'tess': 'lav', 'google': 'lv'}, 'lithuanian': {'tess': 'lit', 'google': 'lt'}, 'luxembourgish': {'tess': 'ltz', 'google': 'lb'}, 'malayalam': {'tess': 'mal', 'google': 'ml'}, 'marathi': {'tess': 'mar', 'google': 'mr'}, 'macedonian': {'tess': 'mkd', 'google': 'mk'}, 'maltese': {'tess': 'mlt', 'google': 'mt'}, 'malay': {'tess': 'msa', 'google': 'ms'}, 'nepali': {'tess': 'nep', 'google': 'ne'}, 'dutch': {'tess': 'nld', 'google': 'nl'}, 'norwegian': {'tess': 'nor', 'google': 'no'}, 'punjabi': {'tess': 'pan', 'google': 'pa'}, 'polish': {'tess': 'pol', 'google': 'pl'}, 'portuguese': {'tess': 'por', 'google': 'pt'}, 'pashto': {'tess': 'pus', 'google': 'ps'}, 'romanian': {'tess': 'ron', 'google': 'ro'}, 'russian': {'tess': 'rus', 'google': 'ru'}, 'sanskrit': {'tess': 'san', 'google': 'sa'}, 'sinhala': {'tess': 'sin', 'google': 'si'}, 'slovak': {'tess': 'slk', 'google': 'sk'}, 'slovenian': {'tess': 'slv', 'google': 'sl'}, 'sindhi': {'tess': 'snd', 'google': 'sd'}, 'spanish': {'tess': 'spa', 'google': 'es'}, 'albanian': {'tess': 'sqi', 'google': 'sq'}, 'serbian': {'tess': 'srp', 'google': 'sr'}, 'sundanese': {'tess': 'sun', 'google': 'su'}, 'swahili': {'tess': 'swa', 'google': 'sw'}, 'swedish': {'tess': 'swe', 'google': 'sv'}, 'tamil': {'tess': 'tam', 'google': 'ta'}, 'tatar': {'tess': 'tat', 'google': 'tt'}, 'telugu': {'tess': 'tel', 'google': 'te'}, 'tajik': {'tess': 'tgk', 'google': 'tg'}, 'thai': {'tess': 'tha', 'google': 'th'}, 'tigrinya': {'tess': 'tir', 'google': 'ti'}, 'turkish': {'tess': 'tur', 'google': 'tr'}, 'uyghur': {'tess': 'uig', 'google': 'ug'}, 'ukrainian': {'tess': 'ukr', 'google': 'uk'}, 'urdu': {'tess': 'urd', 'google': 'ur'}, 'uzbek': {'tess': 'uzb', 'google': 'uz'}, 'vietnamese': {'tess': 'vie', 'google': 'vi'}, 'yiddish': {'tess': 'yid', 'google': 'yi'}, 'yoruba': {'tess': 'yor', 'google': 'yo'}}
voice_lang_map={'afrikaans': {'sr': 'af-ZA', 'google': 'af'}, 'albanian': {'sr': 'sq-AL', 'google': 'sq'}, 'amharic': {'sr': 'am-ET', 'google': 'am'}, 'arabic': {'sr': 'ar-DZ', 'google': 'ar'}, 'armenian': {'sr': 'hy-AM', 'google': 'hy'}, 'azerbaijani': {'sr': 'az-AZ', 'google': 'az'}, 'basque': {'sr': 'eu-ES', 'google': 'eu'}, 'bengali': {'sr': 'bn-BD', 'google': 'bn'}, 'bosnian': {'sr': 'bs-BA', 'google': 'bs'}, 'bulgarian': {'sr': 'bg-BG', 'google': 'bg'}, 'myanmar': {'sr': 'my-MM', 'google': 'my'}, 'catalan': {'sr': 'ca-ES', 'google': 'ca'}, 'croatian': {'sr': 'hr-HR', 'google': 'hr'}, 'czech': {'sr': 'cs-CZ', 'google': 'cs'}, 'danish': {'sr': 'da-DK', 'google': 'da'}, 'dutch': {'sr': 'nl-BE', 'google': 'nl'}, 'english': {'sr': 'en-AU', 'google': 'en'}, 'estonian': {'sr': 'et-EE', 'google': 'et'}, 'finnish': {'sr': 'fi-FI', 'google': 'fi'}, 'french': {'sr': 'fr-BE', 'google': 'fr'}, 'galician': {'sr': 'gl-ES', 'google': 'gl'}, 'georgian': {'sr': 'ka-GE', 'google': 'ka'}, 'german': {'sr': 'de-AT', 'google': 'de'}, 'greek': {'sr': 'el-GR', 'google': 'el'}, 'gujarati': {'sr': 'gu-IN', 'google': 'gu'}, 'hebrew': {'sr': 'iw-IL', 'google': 'iw'}, 'hindi': {'sr': 'hi-IN', 'google': 'hi'}, 'hungarian': {'sr': 'hu-HU', 'google': 'hu'}, 'icelandic': {'sr': 'is-IS', 'google': 'is'}, 'indonesian': {'sr': 'id-ID', 'google': 'id'}, 'italian': {'sr': 'it-IT', 'google': 'it'}, 'japanese': {'sr': 'ja-JP', 'google': 'ja'}, 'kannada': {'sr': 'kn-IN', 'google': 'kn'}, 'kazakh': {'sr': 'kk-KZ', 'google': 'kk'}, 'khmer': {'sr': 'km-KH', 'google': 'km'}, 'kinyarwanda': {'sr': 'rw-RW', 'google': 'rw'}, 'korean': {'sr': 'ko-KR', 'google': 'ko'}, 'lao': {'sr': 'lo-LA', 'google': 'lo'}, 'latvian': {'sr': 'lv-LV', 'google': 'lv'}, 'lithuanian': {'sr': 'lt-LT', 'google': 'lt'}, 'macedonian': {'sr': 'mk-MK', 'google': 'mk'}, 'malay': {'sr': 'ms-MY', 'google': 'ms'}, 'malayalam': {'sr': 'ml-IN', 'google': 'ml'}, 'marathi': {'sr': 'mr-IN', 'google': 'mr'}, 'mongolian': {'sr': 'mn-MN', 'google': 'mn'}, 'nepali': {'sr': 'ne-NP', 'google': 'ne'}, 'norwegian': {'sr': 'no-NO', 'google': 'no'}, 'persian': {'sr': 'fa-IR', 'google': 'fa'}, 'polish': {'sr': 'pl-PL', 'google': 'pl'}, 'portuguese': {'sr': 'pt-BR', 'google': 'pt'}, 'punjabi': {'sr': 'pa-Guru-IN', 'google': 'pa'}, 'romanian': {'sr': 'ro-RO', 'google': 'ro'}, 'russian': {'sr': 'ru-RU', 'google': 'ru'}, 'serbian': {'sr': 'sr-RS', 'google': 'sr'}, 'sinhala': {'sr': 'si-LK', 'google': 'si'}, 'slovak': {'sr': 'sk-SK', 'google': 'sk'}, 'slovenian': {'sr': 'sl-SI', 'google': 'sl'}, 'sesotho': {'sr': 'st-ZA', 'google': 'st'}, 'spanish': {'sr': 'es-AR', 'google': 'es'}, 'sundanese': {'sr': 'su-ID', 'google': 'su'}, 'swahili': {'sr': 'sw-KE', 'google': 'sw'}, 'swedish': {'sr': 'sv-SE', 'google': 'sv'}, 'tamil': {'sr': 'ta-IN', 'google': 'ta'}, 'telugu': {'sr': 'te-IN', 'google': 'te'}, 'thai': {'sr': 'th-TH', 'google': 'th'}, 'tsonga': {'sr': 'ts-ZA', 'google': 'ts'}, 'turkish': {'sr': 'tr-TR', 'google': 'tr'}, 'ukrainian': {'sr': 'uk-UA', 'google': 'uk'}, 'urdu': {'sr': 'ur-IN', 'google': 'ur'}, 'uzbek': {'sr': 'uz-UZ', 'google': 'uz'}, 'vietnamese': {'sr': 'vi-VN', 'google': 'vi'}, 'xhosa': {'sr': 'xh-ZA', 'google': 'xh'}, 'zulu': {'sr': 'zu-ZA', 'google': 'zu'}}
paddleocr_languages = {
    "English": "en",
    "Chinese": "ch",
    "French": "fr",
    "German": "de",
    "Italian": "it",
    "Spanish": "es",
    "Portuguese": "pt",
    "Russian": "ru",
    "Hindi": "hi",
    "Bengali": "bn",
    "Arabic": "ar",
    "Tamil": "ta",
    "Telugu": "te",
    "Marathi": "mr",
    "Kannada": "kn",
    "Malayalam": "ml",
    "Gujarati": "gu",
    "Punjabi": "pa",
    "Urdu": "ur",
    "Persian": "fa",
    "Korean": "ko",
    "Japanese": "ja",
    "Thai": "th",
    "Vietnamese": "vi",
    "Swahili": "sw",
    "Hebrew": "he"
}

api_langs = {
    "Arabic": "ar",
    "Assamese": "as",
    "Bengali": "bn",
    "Belarusian": "be",
    "Bulgarian": "bg",
    "Chinese (Simplified)": "zh-Hans",
    "Chinese (Traditional)": "zh-Hant",
    "Greek": "el",
    "Gujarati": "gu",
    "Hebrew": "he",
    "Hindi": "hi",
    "Japanese": "ja",
    "Kannada": "kn",
    "Kazakh": "kk",
    "Korean": "ko",
    "Kyrgyz": "ky",
    "Macedonian": "mk",
    "Malayalam": "ml",
    "Marathi": "mr",
    "Mongolian": "mn",
    "Odia": "or",
    "Persian": "fa",
    "Punjabi": "pa",
    "Russian": "ru",
    "Serbian (Cyrillic)": "sr-Cyrl",
    "Sindhi": "sd",
    "Sinhala": "si",
    "Tajik": "tg",
    "Tamil": "ta",
    "Tatar": "tt",
    "Telugu": "te",
    "Thai": "th",
    "Ukrainian": "uk",
    "Urdu": "ur"
}